overrides:
  - files:
      - "*.java"
    options:
      printWidth: 81
      tabWidth: 4
      useTabs: true
      trailingComma: none
      semi: true
      bracketSpacing: false
      singleAttributePerLine: false
      
      