####
FROM maven:3-openjdk-11-slim as builder
WORKDIR /build

COPY ./ms-sharekernel/pom.xml ./ms-sharekernel/pom.xml
COPY ./ms-pago-domain/pom.xml ./ms-pago-domain/pom.xml
COPY ./ms-pago-application/pom.xml ./ms-pago-application/pom.xml
COPY ./ms-pago-infraestructure/pom.xml ./ms-pago-infraestructure/pom.xml
COPY ./ms-pago-webapi/pom.xml ./ms-pago-webapi/pom.xml
COPY ./pom.xml ./pom.xml

RUN mvn -q -ntp -B -pl ms-sharekernel -am dependency:go-offline
COPY ms-sharekernel ms-sharekernel
RUN mvn -q -B -pl ms-sharekernel install

RUN mvn -q -ntp -B -pl ms-pago-domain -am dependency:go-offline
COPY ms-pago-domain ms-pago-domain
RUN mvn -q -B -pl ms-pago-domain install

RUN mvn -q -ntp -B -pl ms-pago-application -am dependency:go-offline
COPY ms-pago-application ms-pago-application
RUN mvn -q -B -pl ms-pago-application install

RUN mvn -q -ntp -B -pl ms-pago-infraestructure -am dependency:go-offline
COPY ms-pago-infraestructure ms-pago-infraestructure
RUN mvn -q -B -pl ms-pago-infraestructure install

RUN mvn -q -ntp -B -pl ms-pago-webapi -am dependency:go-offline
COPY ms-pago-webapi ms-pago-webapi
RUN mvn -q -ntp -B -pl ms-sharekernel,ms-pago-domain,ms-pago-application,ms-pago-infraestructure,ms-pago-webapi package

RUN mkdir -p /jar-layers
WORKDIR /jar-layers
RUN java -Djarmode=layertools -jar /build/ms-pago-webapi/target/ms-pago-webapi-0.0.1-exec.jar extract

####
FROM openjdk:18-alpine

WORKDIR /app

COPY ./ms-sharekernel ./ms-sharekernel
COPY ./ms-pago-domain ./ms-pago-domain
COPY ./ms-pago-application ./ms-pago-application
COPY ./ms-pago-infraestructure ./ms-pago-infraestructure
COPY ./ms-pago-webapi ./ms-pago-webapi
COPY ./report-aggregate-module ./report-aggregate-module
COPY ./pom.xml ./pom.xml

ARG MYSQL_HOST=host.docker.internal
ARG MYSQL_PORT=3306
ARG MYSQL_DB=jcdb
ARG MYSQL_USER=jcspz0
ARG MYSQL_PASS=juancarlos
ARG APP_PORT=8081
ARG ARG_SPRING_PROFILES_ACTIVE=docker

ARG AMQP_HOST=159.223.144.204
ARG AMQP_PORT=5672
ARG AMQP_USER=guest
ARG AMQP_PASS=guest

ENV ENV_MYSQL_HOST=${MYSQL_HOST}
ENV ENV_MYSQL_PORT=${MYSQL_PORT}
ENV ENV_MYSQL_DB=${MYSQL_DB}
ENV ENV_MYSQL_USER=${MYSQL_USER}
ENV ENV_MYSQL_PASS=${MYSQL_PASS}
ENV ENV_APP_PORT=${APP_PORT}
ENV SPRING_PROFILES_ACTIVE=${ARG_SPRING_PROFILES_ACTIVE}

ENV ENV_AMQP_HOST=${AMQP_HOST}
ENV ENV_AMQP_PORT=${AMQP_PORT}
ENV ENV_AMQP_USER=${AMQP_USER}
ENV ENV_AMQP_PASS=${AMQP_PASS}

COPY --from=builder /jar-layers/dependencies/ ./
COPY --from=builder /jar-layers/spring-boot-loader/ ./
COPY --from=builder /jar-layers/snapshot-dependencies/ ./
COPY --from=builder /jar-layers/application/ ./

ENTRYPOINT ["java", "org.springframework.boot.loader.JarLauncher"]


